# Server config
server:
  port: ${PORT:8082}

# Spring config
spring:
  application:
    name: auth-service
  logging:
    level:
      org.springframework: WARN
      org.hibernate: WARN
  main.allow-bean-definition-overriding: true
  profiles.active: local

# Eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

# Ribbon config
ribbon:
  eureka:
    enabled: true
    
  